services:
  db:
    image: postgres
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 3s
      retries: 5
      start_period: 30s
    environment:
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
    expose:
      - 5432
    networks:
      - batchernet
    volumes: 
      - db:/var/lib/postgresql/data
    
  app:
    image: batcherapp:latest
    restart: always
    depends_on:
      db:
        condition: service_healthy
    ports:
      - 8080:8080
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_NAME=${DB_NAME}
    networks:
      - batchernet

networks:
  batchernet:
    driver: bridge

volumes:
  db:
    driver: local